#!/bin/bash
set -x
config-pin overlay cape-universal
config-pin P9.24 can
config-pin P9.26 can
modprobe can
modprobe can-dev
modprobe can-raw
sleep 1
ip link set can1 up type can bitrate 1000000
ifconfig can1 up

# move trinamic motor
cansend can1  001#04.01.00.00.0f.ff.e7.00

